version: '3'
 
services:
    container-api:
        image: rsd23/lamoda-container-api
        environment:
            DB_HOST: mongodb
            DB_PORT: 27017
            DB_DATABASE: lamoda-quest
            DB_USERNAME: root
            DB_PASSWORD: example

    container-app:
        build: .
        environment:
            CONTAINER_API_URL: http://nginx:8082/v1/
            CONTAINER_ROLE: app
            DB_HOST: mongodb
            DB_PORT: 27017
            DB_DATABASE: lamoda-quest
            DB_USERNAME: root
            DB_PASSWORD: example
            REDIS_HOST: redis-server
            REDIS_PORT: 6379

    container-app-queue:
        build: .
        environment:
            CONTAINER_API_URL: http://nginx:8082/v1/
            CONTAINER_ROLE: queue
            DB_HOST: mongodb
            DB_PORT: 27017
            DB_DATABASE: lamoda-quest
            DB_USERNAME: root
            DB_PASSWORD: example
            REDIS_HOST: redis-server
            REDIS_PORT: 6379

    redis-server:
        image: redis:alpine
        ports:
            - 6379:6379
        restart: always

    mongodb:
        image: mongo
        ports:
            - 27018:27017
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: lamoda-quest

    nginx:
        image: nginx
        ports:
            - 8081:8081
            - 8082:8082
        volumes:
            - ./src:/app
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - container-api
            - container-app